// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBxvZvke-YCTfcWsYp3GK2FVf7RTE6tOrs",
    authDomain: "socialtec-f33c3.firebaseapp.com",
    projectId: "socialtec-f33c3",
    storageBucket: "socialtec-f33c3.appspot.com",
    messagingSenderId: "65390635798",
    appId: "1:65390635798:web:d3fb6ed3edac0c20367e37",
    measurementId: "G-XE27ZQXC40"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxvZvke-YCTfcWsYp3GK2FVf7RTE6tOrs',
    appId: '1:65390635798:android:0afb502fff36338c367e37',
    messagingSenderId: '65390635798',
    projectId: 'socialtec-f33c3',
    //storageBucket: 'gs://look-back-90825.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyC_dbguB0bWDNuw3N8kF3ORkgidDDG2d6I',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );
}
